# -*- mode: python ; coding: utf-8 -*-


from PyInstaller.utils.hooks import collect_data_files

flet_data = collect_data_files('flet')
a = Analysis(
    ['obfuscated_src\\main.py'],
    pathex=['obfuscated_src'],
    binaries=[],
    datas=flet_data,
    hiddenimports=[
        'pyarmor_runtime_000000',
        'desktop_alkozon',
        'desktop_alkozon.config',
        'desktop_alkozon.core',
        'desktop_alkozon.core.auth',
        'desktop_alkozon.core.connectivity',
        'desktop_alkozon.core.database',
        'desktop_alkozon.core.encryption',
        'desktop_alkozon.core.exceptions',
        'desktop_alkozon.core.i18n',
        'desktop_alkozon.core.logger',
        'desktop_alkozon.core.outbox',
        'desktop_alkozon.core.repository',
        'desktop_alkozon.core.sync_manager',
        'desktop_alkozon.features',
        'desktop_alkozon.features.deliveries',
        'desktop_alkozon.features.deliveries.controller',
        'desktop_alkozon.features.deliveries.service',
        'desktop_alkozon.features.deliveries.views',
        'desktop_alkozon.features.employees',
        'desktop_alkozon.features.employees.controller',
        'desktop_alkozon.features.employees.service',
        'desktop_alkozon.features.employees.views',
        'desktop_alkozon.features.warehouse',
        'desktop_alkozon.features.warehouse.controller',
        'desktop_alkozon.features.warehouse.service',
        'desktop_alkozon.features.warehouse.views',
        'desktop_alkozon.models',
        'desktop_alkozon.models.api_models',
        'desktop_alkozon.services',
        'desktop_alkozon.services.api_client',
        'desktop_alkozon.ui',
        'desktop_alkozon.ui.components',
        'desktop_alkozon.ui.components.connectivity_banner',
        'desktop_alkozon.ui.components.settings_drawer',
        'desktop_alkozon.ui.pages',
        'desktop_alkozon.ui.pages.login_page',
        'desktop_alkozon.ui.pages.main_menu',
        'desktop_alkozon.utils',
        'flet',
        'flet.controls',
        'flet.controls.material',
        'flet.controls.cupertino',
        'httpx',
        'pydantic',
        'cryptography',
        'cryptography.fernet',
        'cryptography.hazmat',
        'cryptography.hazmat.primitives',
        'desktop_alkozon._build_config',
        'aiosqlite',
        'bcrypt',
        'jwt',
        'keyring',
        'dotenv',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Alkozon',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Alkozon',
)
